### ISSUE TITLE
`master_player_lookup` query is invalid

### ISSUE THREAD

**Issue by michael-long88** [nathanbraun/fantasy-developer-kit#1]
The GraphQL query [the function](https://github.com/nathanbraun/fantasy-developer-kit/blob/cf80547990f92afbd1c0e1833d3d93fda62dbb0a/utilities.py#L96) runs references `fantasymath_id` and `position`. The [API schema](https://api.sims.fantasymath.com/) has `pos` which is obviously `position` in the original query, but is `player_id` the replacement for `fantasymath_id`?

**Comment by nathanbraun** [comment]
Yeah it is, I'm updating this in a sec with more info.

**Comment by nathanbraun** [comment]
Ok it's updated -- all the functions in utilities.py should work (including master_player_lookup) but I haven't gotten a chance to update all the text of the guide/code for projects yet (except the first WDIS one).  Will do that ASAP.
