### ISSUE TITLE
Error when testing utilities.py

### ISSUE THREAD

**Issue by jboone0052** [nathanbraun/fantasy-developer-kit#3]
In working through the examples, in chapter 3, utilities.py, I'm calling the code to get available players. It's returning an error:

data":null,"errors":[{"message":"(psycopg2.errors.AdminShutdown) terminating connection due to administrator command\\nSSL connection has been closed unexpectedly\\n\

there is some sql commands as well I can provide if necessary, but they don't seem to be the reason for the error. This is most likely an issue with fantasymath api, but not sure if you are affiliated with fantasymath in some way or not, so I'm starting here as the code is in the developer kit book.  I am able to retrieve a toke successfully though.

**Comment by nathanbraun** [comment]
Hi @jboone0052 thanks for letting me know about this.  I do run the fantasy math API -- I was messing around with it recently and apparently broke something.  I think it's working now but definitely let me know if it's not.

**Comment by jboone0052** [comment]
Thank you, it is working now!
